# Generated by Django 4.0.3 on 2022-04-26 23:03

import ckeditor.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('subtitle', models.CharField(max_length=80)),
                ('info', ckeditor.fields.RichTextField(default='No hay información aún')),
                ('image', models.ImageField(blank=True, null=True, upload_to='media_stge')),
                ('user', models.CharField(max_length=15)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
