# Generated by Django 4.0.3 on 2022-04-27 02:00

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Smart_Contracts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case', models.CharField(max_length=40)),
                ('info', ckeditor.fields.RichTextField(default='No se ha cargado información')),
                ('user', models.CharField(default='Desconocido', max_length=20)),
            ],
        ),
    ]
