# Generated by Django 4.0.3 on 2022-04-19 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_extension',
            name='link',
            field=models.URLField(blank=True, default='', null=True),
        ),
    ]
