# Generated by Django 4.0.3 on 2022-04-26 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_extension_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_extension',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars'),
        ),
    ]
