# Generated by Django 4.0.3 on 2022-04-26 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_extension_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_extension',
            name='has_avatar',
            field=models.BooleanField(default=False),
        ),
    ]
