# Generated by Django 4.0.3 on 2022-04-26 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_extension_has_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_extension',
            name='has_avatar',
        ),
        migrations.AlterField(
            model_name='user_extension',
            name='avatar',
            field=models.ImageField(blank=True, default='avatars/Bitcoin-Logo.png', null=True, upload_to='avatars'),
        ),
    ]
