# Generated by Django 4.0.3 on 2022-04-27 01:34

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NFTs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=15)),
                ('title', models.CharField(max_length=15)),
                ('info', ckeditor.fields.RichTextField(default='No se ha cargado información')),
            ],
        ),
    ]
