# Generated by Django 4.0.3 on 2022-03-21 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('functionalities', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experience',
            old_name='user_name',
            new_name='user',
        ),
    ]
