# Generated by Django 4.0.3 on 2022-04-11 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('functionalities', '0002_rename_user_name_experience_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
