# Generated by Django 4.0.3 on 2022-04-16 16:10

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('functionalities', '0003_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='coin',
            name='info',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
