# Generated by Django 4.0.3 on 2022-04-17 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('functionalities', '0006_rename_name_nfts_title_remove_nfts_value_nfts_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nfts',
            name='user',
            field=models.CharField(max_length=15),
        ),
    ]
