# Generated by Django 4.0.3 on 2022-04-17 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('functionalities', '0007_alter_nfts_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smart_contracts',
            name='case',
            field=models.CharField(max_length=40),
        ),
    ]
