# Generated by Django 4.0.3 on 2022-04-17 22:26

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('functionalities', '0008_alter_smart_contracts_case'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('subtitle', models.CharField(max_length=80)),
                ('image', models.ImageField(upload_to='')),
                ('user', models.CharField(max_length=15)),
            ],
        ),
        migrations.AlterField(
            model_name='nfts',
            name='info',
            field=ckeditor.fields.RichTextField(default='No se ha cargado información'),
        ),
        migrations.AlterField(
            model_name='smart_contracts',
            name='info',
            field=ckeditor.fields.RichTextField(default='No se ha cargado información'),
        ),
    ]
