# Generated by Django 4.0.3 on 2022-04-17 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('functionalities', '0009_article_alter_nfts_info_alter_smart_contracts_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='smart_contracts',
            name='user',
            field=models.CharField(default='Desconocido', max_length=20),
        ),
    ]
