# Generated by Django 4.0.3 on 2022-04-18 20:15

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('functionalities', '0010_smart_contracts_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='experience',
            field=ckeditor.fields.RichTextField(default='No se ha cargado información'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='ocupation',
            field=models.CharField(max_length=20),
        ),
    ]
