# Generated by Django 4.0.3 on 2022-04-18 23:19

import ckeditor.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('functionalities', '0011_alter_experience_experience_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='article',
            name='info',
            field=ckeditor.fields.RichTextField(default='No hay información aún'),
        ),
    ]
