# Generated by Django 4.0.3 on 2022-04-19 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('functionalities', '0012_article_date_article_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media_stge'),
        ),
    ]
